# Generated by Django 3.0.6 on 2020-06-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='brands',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='favoriteid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='front_img',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='nutrigrade',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='productid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='quantity',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='replacedarticle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='replacedid',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='replacednutrigrade',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='stores',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='userid',
            field=models.CharField(max_length=255),
        ),
    ]
