# Generated by Django 3.0.6 on 2020-06-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfacts', '0002_auto_20200610_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='replacedid',
            field=models.IntegerField(),
        ),
    ]
