# Generated by Django 3.0.6 on 2020-06-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfacts', '0003_auto_20200610_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='idcategories',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='brands',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='carbs_100g',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='energy_kcal_100g',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='fat_100g',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='fiber_100g',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='front_img',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='idproduct',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='ingredients_img',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='nutrigrade',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='nutrition_Score_100g',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='nutrition_img',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='productname',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='proteins_100g',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='salt_100g',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='saturated_fat_100g',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='sodium_100g',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='stores',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='sugars_100g',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
