# Generated by Django 3.0.8 on 2020-07-17 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodfacts', '0004_auto_20200610_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='brands',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='stores',
        ),
    ]
