# Generated by Django 3.0.8 on 2020-07-17 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodfacts', '0005_auto_20200717_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='replacedarticle',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='replacednutrigrade',
        ),
    ]
